version: "3.9"

networks:
  account_demo_network:
    driver: bridge

services:
  accounts-server:
    build:
      context: .
      dockerfile: ./server.Dockerfile
    networks:
      - account_demo_network
    restart: always
    environment:
      API_PRIVATE_KEY: ${API_PRIVATE_KEY}
    ports:
      - 1323:1323

  accounts-frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    networks:
      - account_demo_network
    ports:
      - 3000:3000
    restart: always
